name: CI - Azure Databricks Retail Lakehouse

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest black flake8 isort

    # 4. Run code quality checks
    - name: Lint with flake8
      run: |
        flake8 src tests --max-line-length=100

    - name: Check formatting with Black
      run: |
        black --check src tests

    - name: Sort imports with isort
      run: |
        isort --check-only src tests

    # 5. Run unit tests
    - name: Run pytest
      run: pytest -q --tb=short --disable-warnings
